### ISSUE TITLE
Reference to GOOMPH_PDE_VER missing in subproject scripts ?

### ISSUE THREAD

**Issue by antoine-morvan** [diffplug/goomph-eclipse-plugin#1]
Hi,

While trying out Goomph plug-ins with the example from this repo, the following questions came up :

I am wondering if the "repoEclipse '4.6.0'" line in ide/build.gradle should reference the GOOMPH_PDE_VER from gradle.properties ? If not, why? (same applies for target.p2/build.gradle with "repoEclipse '4.5.2'")

Best regards.

**Comment by nedtwigg** [comment]
It could be, but it doesn't need to be.  You can develop an eclipse plugin for an older version of eclipse using a newer version of the IDE.
